spring.application.name=transacciones-service
server.port=8082
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/banco_bff}
spring.datasource.username=${DB_USER:banco_user}
spring.datasource.password=${DB_PASSWORD:banco_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=transacciones-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.listener.ack-mode=record
banco.kafka.topic.retiros=${KAFKA_RETIROS_TOPIC:banco.retiros}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
info.app.nombre=Servicio de transacciones Banco XYZ
info.app.canal=backend
info.app.eventos=Consumidor Kafka de retiros
