CREATE TABLE IF NOT EXISTS cuentas (
    id BIGINT PRIMARY KEY,
    nombre VARCHAR(120) NOT NULL,
    saldo NUMERIC(15, 2) NOT NULL CHECK (saldo >= 0),
    edad INTEGER NOT NULL CHECK (edad BETWEEN 18 AND 120),
    tipo VARCHAR(30) NOT NULL CHECK (tipo IN ('AHORRO', 'PRESTAMO', 'HIPOTECA')),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    moneda VARCHAR(3) NOT NULL DEFAULT 'CLP',
    version BIGINT NOT NULL DEFAULT 0,
    fecha_actualizacion TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transacciones (
    id BIGSERIAL PRIMARY KEY,
    cuenta_id BIGINT NOT NULL REFERENCES cuentas(id),
    fecha DATE NOT NULL,
    tipo VARCHAR(20) NOT NULL CHECK (tipo IN ('CREDITO', 'DEBITO')),
    monto NUMERIC(15, 2) NOT NULL CHECK (monto > 0),
    descripcion VARCHAR(255),
    canal VARCHAR(30) NOT NULL DEFAULT 'LEGACY',
    anomalia BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_transacciones_cuenta_fecha
    ON transacciones(cuenta_id, fecha DESC);

CREATE TABLE IF NOT EXISTS eventos_procesados (
    evento_id VARCHAR(80) PRIMARY KEY,
    tipo_evento VARCHAR(50) NOT NULL,
    procesado_en TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
