spring.application.name=api-gateway
server.port=8080
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://localhost:8180/realms/banco-xyz}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:8180/realms/banco-xyz/protocol/openid-connect/certs}

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
info.app.nombre=API Gateway seguro Banco XYZ
info.app.seguridad=OAuth2 con JWT
