spring.application.name=bff-atm
server.port=8093
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

backend.cuentas.url=${CUENTAS_SERVICE_URL:http://CUENTAS-SERVICE}
bff.atm.api-key=${ATM_API_KEY:BANCO-XYZ-ATM-2026}

resilience4j.circuitbreaker.instances.cuentas.sliding-window-size=5
resilience4j.circuitbreaker.instances.cuentas.minimum-number-of-calls=2
resilience4j.circuitbreaker.instances.cuentas.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.cuentas.wait-duration-in-open-state=10s

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
info.app.nombre=BFF Cajero Banco XYZ
info.app.canal=atm
info.app.resiliencia=Resilience4j con Circuit Breaker y fallback
